name: Executar ETL Prolog

on:
  schedule:
    - cron: '0 8 * * *'    # 05:00 hor치rio de Bras칤lia (UTC+3)
    - cron: '0 15 * * *'   # 12:00 hor치rio de Bras칤lia (UTC+3)
  workflow_dispatch:       # Executar manualmente

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Clonar o reposit칩rio
        uses: actions/checkout@v3

      - name: 游냀 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 游닍 Instalar depend칡ncias
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip  # Atualizando pip
          pip install -r estrutura_prolog/requirements.txt


      - name: 游닍 Verificar se o ambiente virtual foi ativado
        run: |
          which python
          which pip

      - name: 游댏 Criar arquivo .env
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "API_KEY_PROLOG=${{ secrets.API_KEY_PROLOG }}" >> .env

      - name: 游댌 Verificar estrutura de diret칩rios
        run: |
          ls -l estrutura_prolog/src/

      - name: 游 Executar ETL
        run: |
          source .venv/bin/activate
          python estrutura_prolog/src/main.py
